use comics;
insert into genres (genre, description) values ('Action', 'A work typically depicting fighting, violence, chaos, and fast paced motion.');
insert into genres (genre, description) values ('Adult', 'Contains content that is suitable only for adults. Titles in this category may include prolonged scenes of intense violence and/or graphic sexual content and nudity.');
insert into genres (genre, description) values ('Adventure', 'If a character in the story goes on a trip or along that line, your best bet is that it is an adventure manga. Otherwise, it\'s up to your personal prejudice on this case.');
insert into genres (genre, description) values ('Comedy', 'A dramatic work that is light and often humorous or satirical in tone and that usually contains a happy resolution of the thematic conflict.');
insert into genres (genre, description) values ('Doujinshi', 'Fan based work inspired by official anime or manga. For MangaUpdates, original works DO NOT fall under this category');
insert into genres (genre, description) values ('Drama', 'A work meant to bring on an emotional response, such as instilling sadness or tension.');
insert into genres (genre, description) values ('Ecchi', 'Possibly the line between hentai and non-hentai, ecchi usually refers to fanservice put in to attract a certain group of fans.');
insert into genres (genre, description) values ('Fantasy', 'Anything that involves, but not limited to, magic, dream world, and fairy tales.');
insert into genres (genre, description) values ('Gender Bender', 'Girls dressing up as guys, guys dressing up as girls.. Guys turning into girls, girls turning into guys.. I think you get the picture.');
insert into genres (genre, description) values ('Harem', 'A series involving one male character and many female characters (usually attracted to the male character). A Reverse Harem is when the genders are reversed.');
insert into genres (genre, description) values ('Hentai', 'Adult sexual content in an illustrated form where the FOCUS of the manga is placed on sexually graphic acts.');
insert into genres (genre, description) values ('Historical', 'Having to do with old or ancient times.');
insert into genres (genre, description) values ('Horror', 'A painful emotion of fear, dread, and abhorrence; a shuddering with terror and detestation; the feeling inspired by something frightful and shocking.');
insert into genres (genre, description) values ('Josei', 'Literally "Woman". Targets women 18-30. Female equivalent to seinen. Unlike shoujo the romance is more realistic and less idealized. The storytelling is more explicit and mature.');
insert into genres (genre, description) values ('Lolicon', 'Representing a sexual attraction to young or under-age girls.');
insert into genres (genre, description) values ('Martial Arts', 'As the name suggests, anything martial arts related. Any of several arts of combat or self-defense, such as aikido, karate, judo, or tae kwon do, kendo, fencing, and so on and so forth.');
insert into genres (genre, description) values ('Mature', 'Contains subject matter which may be too extreme for people under the age of 17. Titles in this category may contain intense violence, blood and gore, sexual content and/or strong language.');
insert into genres (genre, description) values ('Mecha', 'A work involving and usually concentrating on all types of large robotic machines.');
insert into genres (genre, description) values ('Mystery', 'Usually an unexplained event occurs, and the main protagonist attempts to find out what caused it.');
insert into genres (genre, description) values ('Psychological', 'Usually deals with the philosophy of a state of mind, in most cases detailing abnormal psychology.');
insert into genres (genre, description) values ('Romance', 'Any love related story. We will define love as between man and woman in this case. Other than that, it is up to your own imagination of what love is.');
insert into genres (genre, description) values ('School Life', 'Having a major setting of the story deal with some type of school.');
insert into genres (genre, description) values ('Sci-fi', 'Short for science fiction, these works involve twists on technology and other science related phenomena which are contrary or stretches of the modern day scientific world.');
insert into genres (genre, description) values ('Seinen', 'From Google: Seinen means "young Man." Manga and anime that specifically targets young adult males around the ages of 18 to 25 are seinen titles. The stories in seinen works appeal to university students and those in the working world. Typically the story lines deal with the issues of adulthood.');
insert into genres (genre, description) values ('Shotacon', 'Representing a sexual attraction to young or under-age boys.');
insert into genres (genre, description) values ('Shoujo', 'A work intended and primarily written for females. Usually involves a lot of romance and strong character development.');
insert into genres (genre, description) values ('Shoujo Ai', 'Often synonymous with yuri, this can be thought of as somewhat less extreme. "Girl\'s Love", so to speak.');
insert into genres (genre, description) values ('Shounen', 'A work intended and primarily written for males. These works usually involve fighting and/or violence.');
insert into genres (genre, description) values ('Shounen Ai', 'Often synonymous with yaoi, this can be thought of as somewhat less extreme. "Boy\'s Love", so to speak.');
insert into genres (genre, description) values ('Slice of Life', 'As the name suggests, this genre represents day-to-day tribulations of one/many character(s). These challenges/events could technically happen in real life and are often -if not all the time- set in the present timeline in a world that mirrors our own.');
insert into genres (genre, description) values ('Smut', 'Deals with series that are considered profane or offensive, particularly with regards to sexual content');
insert into genres (genre, description) values ('Sports', 'As the name suggests, anything sports related. Baseball, basketball, hockey, soccer, golf, and racing just to name a few.');
insert into genres (genre, description) values ('Supernatural', 'Usually entails amazing and unexplained powers or events which defy the laws of physics.');
insert into genres (genre, description) values ('Tragedy', 'Contains events resulting in great loss and misfortune.');
insert into genres (genre, description) values ('Yaoi', 'This work usually involves intimate relationships between men.');
insert into genres (genre, description) values ('Yuri', 'This work usually involves intimate relationships between women.');
